apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kevin-demo
spec:
  tasks:
    - name: build
      taskRef:
        name: kaniko
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: kubernetes-actions
